// This file has been autogenerated from a class added in the UI designer.

using System;
using ForceTouchNavigationSample.ViewModels;
using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Binding.iOS.Views;
using MvvmCross.iOS.Views;
using UIKit;

namespace ForceTouchNavigationSample
{
    [MvxFromStoryboard("Main")]
    [MvvmCross.iOS.Views.Presenters.Attributes.MvxChildPresentation]
	public partial class ChildViewController : MvxViewController<ChildViewModel>
	{
        private MvxImageViewLoader _imageLoader;

        public ChildViewController (IntPtr handle) : base (handle)
		{
		}

		public string ImageUrl
		{
			get { return _imageLoader?.ImageUrl; }
			set { _imageLoader.ImageUrl = value; }
		}


		public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            _imageLoader = new MvxImageViewLoader(() => AvatarImageView, AvatarImageView.SetNeedsLayout);

            var set = this.CreateBindingSet<ChildViewController, ChildViewModel>();

			set.Bind(FullNameLabel).To(x => x.Emplyee.FullName);
            set.Bind(EmailLabel).To(x => x.Emplyee.Email);
			set.Bind(PositionLabel).To(x => x.Emplyee.Position);
            set.Bind(DetailLabel).To(x => x.Emplyee.Description);
            set.Bind().For(x => x.ImageUrl).To(x=> x.Emplyee.AvatarUrl);

            set.Apply();
        }
	}
}
